In [2]:
import numpy as np
import pandas as pd

In [11]:
# 6.3.1 ダイエットのデータ
df = pd.DataFrame(
    {
        "炭水化物": [
            33,
            40,
            37,
            27,
            30,
            43,
            34,
            48,
            30,
            38,
            50,
            51,
            30,
            36,
            41,
            42,
            46,
            24,
            35,
            37,
        ],
        "年齢": [
            33,
            47,
            49,
            35,
            46,
            52,
            62,
            23,
            32,
            42,
            31,
            61,
            63,
            40,
            50,
            64,
            56,
            61,
            48,
            28,
        ],
        "体重": [
            100,
            92,
            135,
            144,
            140,
            101,
            95,
            101,
            98,
            105,
            108,
            85,
            130,
            127,
            109,
            107,
            117,
            100,
            118,
            102,
        ],
        "蛋白": [
            14,
            15,
            18,
            12,
            15,
            15,
            14,
            17,
            15,
            14,
            17,
            19,
            19,
            20,
            15,
            16,
            18,
            13,
            18,
            14,
        ],
    }
)

y = df["炭水化物"]
X = df[["年齢", "体重", "蛋白"]]
X.insert(0, "1", 1)

b = (np.linalg.inv(X.T @ X)) @ (X.T @ y)

# 一般化線型モデルにおける不偏分散
sigma_hat_sq = ((y - X @ b).T) @ (y - X @ b) / (len(df) - (len(df.columns) - 1))

In [9]:
sigma_hat_sq = (y.T @ y - y.T @ X @ b - b.T @ X.T @ y + b.T @ X.T @ X @ b) / (
    len(df) - len(X.columns)
)
sigma_hat_sq

35.47892858287628

### 表6.4

In [10]:
pd.DataFrame(
    {
        "項": ["定数項", "年齢に対する係数", "体重に対する係数", "蛋白に対する係数"],
        "推定値": np.round(b, 3),
        "標準誤差": np.round(
            np.sqrt(np.diag(np.linalg.inv(X.T @ X) * sigma_hat_sq)), 3
        ),
    }
).set_index("項")

             推定値    標準誤差
項
定数項       36.960  13.071
年齢に対する係数  -0.114   0.109
体重に対する係数  -0.228   0.083
蛋白に対する係数   1.958   0.635

### 表6.5

In [136]:
X_0 = X.drop(["年齢"], axis=1)
b_0 = np.linalg.inv(X_0.T @ X_0) @ (X_0.T @ y)

p = len(X.columns)
q = len(X_0.columns)

print("年齢なしのモデルによる回帰係数：", b_0)

df_tmp = pd.DataFrame(
    {
        "変動要因": ["モデル(6.7)", "モデル(6.6)による改善", "残差"],
        "自由度": [q, p - q, len(df) - p],
        "平方和": [
            round(b_0.T @ X_0.T @ y, 3),
            round(b.T @ X.T @ y - b_0.T @ X_0.T @ y, 3),
            round(((y - X @ b) ** 2).sum(), 3),
        ],
        "平均平方": [
            np.nan,
            round((b.T @ X.T @ y - b_0.T @ X_0.T @ y) / (p - q), 2),
            round(((y - X @ b) ** 2).sum() / (len(df) - p), 2),
        ],
    }
)
pd.concat(
    [
        df_tmp,
        pd.DataFrame(
            {
                "変動要因": ["計"],
                "自由度": [len(df)],
                "平方和": [
                    round(b_0.T @ X_0.T @ y, 3)
                    + round(b.T @ X.T @ y - b_0.T @ X_0.T @ y, 3)
                    + round(((y - X @ b) ** 2).sum(), 3)
                ],
                "平均平方": np.nan,
            }
        ),
    ],
    axis=0,
).reset_index(drop=True)

年齢なしのモデルによる回帰係数： [33.13031969 -0.22164904  1.82429116]

            変動要因  自由度        平方和   平均平方
0       モデル(6.7)    3  28761.978    NaN
1  モデル(6.6)による改善    1     38.359  38.36
2             残差   16    567.663  35.48
3              計   20  29368.000    NaN

In [13]:
y = np.array([6.8, 6.6, 5.3, 6.1, 7.5, 7.4, 7.2, 6.5, 7.8, 9.1, 8.8, 9.1])

X = np.array(
    [
        [1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0, 0],
        [1, 0, 0, 1, 0, 0],
        [1, 1, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0],
        [1, 1, 0, 1, 1, 0],
        [1, 1, 0, 1, 1, 0],
        [1, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [1, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1],
    ]
)

In [28]:
b = np.linalg.inv(X.T @ X) @ X.T @ y
sigma_hat_sq = ((y - X @ b) ** 2).sum() / (X.shape[0] - X.shape[1])
sigma_hat_sq

0.2466666666666665

In [32]:
np.sqrt(np.diag(np.linalg.inv(X.T @ X) * sigma_hat_sq))

array([0.35118846, 0.49665548, 0.49665548, 0.49665548, 0.70237692,
       0.70237692])

array([6.8, 6.6, 5.3, 6.1, 7.5, 7.4, 7.2, 6.5, 7.8, 9.1, 8.8, 9.1])